// 汉化
export default {
  'Documentation': '文档',
  'General': '常规',
  'Listeners': '监听器',
  'Execution Listener': '扩展监听器',
  'Properties': '属性',
  'Add Property': '添加属性',
  'Extensions': '扩展',
  'Name': '名称',
  'Version Tag': '版本标签',
  'Executable': '可执行',
  'External Task Configuration': '外部任务设置',
  'Task Priority': '任务优先级',
  'Job Configuration': '工作设置',
  'Job Priority': '工作优先级',
  'Element Documentation': '元素文档',
  'Startable': '可启动',
  'History Configuration': '历史设置',
  'History Time To Live': '历史存在时间',
  'Candidate Starter Configuration': '候选启动器配置',
  'Candidate Starter Groups': '候选启动组',
  'Specify more than one group as a comma separated list': '指定一个以上的组作为逗号分隔的列表',
  'Candidate Starter Users': '候选启动器用户',
  'Specify more than one user as a comma separated list.': '指定一个以上的用户作为逗号分隔的列表',
  'Input/Output': '输入/输出',
  'Parameters': '参数',
  'Input Parameters': '输入参数',
  'Output Parameters': '输出参数',
  'Asynchronous Before': '异步前',
  'Asynchronous After': '异步后',
  'Asynchronous Continuations': '异步延续',
  'Create Intermediate/Boundary Event': '创建中间/边界事件',
  'Create Gateway': '创建网关',
  'Tasklist Configuration': '任务列表配置',
  'Forms': '表单',


  // Labels
  'Activate the global connect tool': '启用全局连接工具',
  'Append {type}': '追加{type}',
  'Add Lane above': '在上方添加通道',
  'Divide into two Lanes': '分成两条车道',
  'Divide into three Lanes': '划分为三条车道',
  'Add Lane below': '在下方添加通道',
  'Append compensation activity': '加补偿',
  'Change type': '更改类型',
  'Connect using Association': '连接到协会',
  'Connect using Sequence/MessageFlow or Association': '连接到序列流/消息流或关联',
  'Connect using DataInputAssociation': '连接到DataInputAssociation',
  'Remove': '删除',
  'Activate the hand tool': '激活手动工具',
  'Activate the lasso tool': '启用套索工具',
  'Activate the create/remove space tool': '激活放置/删除工具',
  'Create expanded SubProcess': '创建扩展子流程',
  'Create IntermediateThrowEvent/BoundaryEvent': '创建IntermediateThrowEvent /边界事件',
  'Create Pool/Participant': '创建池/参与者',
  'Parallel Multi Instance': '并行多实例',
  'Sequential Multi Instance': '顺序多实例',
  'Loop': '循环',
  'Ad-hoc': 'ad hoc',
  'Create {type}': '创建{type}',
  'Task': '任务',
  'Send Task': '发送任务(Send Task)',
  'Receive Task': '接收任务(Receive Task)',
  'User Task': '用户任务(User Task)',
  'Manual Task': '手动任务(Manual Task)',
  'Business Rule Task': '业务规则任务(Business Rule Task)',
  'Service Task': '服务任务(Service Task)',
  'Script Task': '脚本任务(Script Task)',
  'Call Activity': '通话活动(Call Activity)',
  'Sub Process (collapsed)': '封闭流程(Sub Process collapsed)',
  'Sub Process (expanded)': '开放流程(Sub Process expanded)',
  'Start Event': '开始活动',
  'Intermediate Throw Event': '中间/边界事件',
  'End Event': '结束事件',
  'Message Start Event': '消息开始事件',
  'Timer Start Event': '时间开始事件',
  'Conditional Start Event': '有条件的开始事件',
  'Signal Start Event': '信号启动事件',
  'Error Start Event': '错误启动事件',
  'Escalation Start Event': 'Escalation Start Event',
  'Compensation Start Event': '补偿开始事件',
  'Message Start Event (non-interrupting)': '消息启动事件（非中断）',
  'Timer Start Event (non-interrupting)': '时间启动事件（非中断）',
  'Conditional Start Event (non-interrupting)': '条件启动事件（非中断）',
  'Signal Start Event (non-interrupting)': '信号启动事件（非中断）',
  'Escalation Start Event (non-interrupting)': '升级开始事件（非中断）',
  'Message Intermediate Catch Event': 'Incoming Message Intermediate Event',
  'Message Intermediate Throw Event': '中间消息中间事件',
  'Timer Intermediate Catch Event': 'Incoming Intermediate Time Event',
  'Escalation Intermediate Throw Event': '触发升级投掷事件',
  'Conditional Intermediate Catch Event': '发生有条件的中间事件',
  'Link Intermediate Catch Event': '传入链接中间事件',
  'Link Intermediate Throw Event': '中间触发的链接事件',
  'Compensation Intermediate Throw Event': '触发中级投掷事件',
  'Signal Intermediate Catch Event': '传入信号中间事件',
  'Signal Intermediate Throw Event': '中级信号中间事件',
  'Message End Event': '消息结束事件',
  'Escalation End Event': 'Escalation End Event',
  'Error End Event': '错误结束事件',
  'Cancel End Event': '终止事件',
  'Compensation End Event': '赔偿结束事件',
  'Signal End Event': '信号结束事件',
  'Terminate End Event': '终止结束事件',
  'Message Boundary Event': '附加消息中间事件',
  'Message Boundary Event (non-interrupting)': '附加消息中间事件（非中断）',
  'Timer Boundary Event': '附加时间中间事件',
  'Timer Boundary Event (non-interrupting)': '附加时间中间事件（非中断）',
  'Escalation Boundary Event': '附加升级中间事件',
  'Escalation Boundary Event (non-interrupting)': '上涨升级中间事件（不中断）',
  'Conditional Boundary Event': '附加条件中间事件',
  'Conditional Boundary Event (non-interrupting)': '附加条件中间事件（非中断）',
  'Error Boundary Event': '附加错误中间事件',
  'Cancel Boundary Event': '附加中断事件',
  'Signal Boundary Event': '附加信号中间事件',
  'Signal Boundary Event (non-interrupting)': '附加信号中间事件（非中断）',
  'Compensation Boundary Event': '附加补偿中间事件',
  'Exclusive Gateway': '独家门户',
  'Parallel Gateway': '并行网关',
  'Inclusive Gateway': '包容性网关',
  'Complex Gateway': '复杂网关',
  'Event based Gateway': '基于事件的网关',
  'Transaction': '交易',
  'Sub Process': '子流程',
  'Event Sub Process': 'Event Subprocess',
  'Collapsed Pool': '封闭泳池',
  'Expanded Pool': 'Expanded Pool',

  // Errors
  'no parent for {element} in {parent}': '{parent}中没有{element}的父元素',
  'no shape type specified': '没有指定形状类型',
  'flow elements must be children of pools/participants': '参与者的孩子',
  'out of bounds release': '越界释放',
  'more than {count} child lanes': '超过{count}泳道儿童',
  'element required': '需要的元素',
  'diagram not part of bpmn:definitionsno diagram to display': '没有流程模型',
  'no process or collaboration to display': '没有流程/协作',
  'element {element} referenced by {referenced}#{property} not yet drawn': '{referenced}＃{property}引用的元素{element}尚未绘制',
  'already rendered {element}': '{element}已经渲染',
  'failed to import {element}': '{element}无法导入'
};
